### ISSUE TITLE
Add cross-origin fetches, media and MIME type attributes

### ISSUE THREAD

**Issue by rizalibnu** [ri7nz/Edotensei#1]
`<link>` element can accept `crossorigin`, `media` and `type` attribute. I think this is very useful to add this feature to your lib.

Reference:
https://developer.mozilla.org/en-US/docs/Web/HTML/Preloading_content#Cross-origin_fetches
https://developer.mozilla.org/en-US/docs/Web/HTML/Preloading_content#Including_media
https://developer.mozilla.org/en-US/docs/Web/HTML/Preloading_content#Including_a_MIME_type

**Comment by ri7nz** [comment]
thank you for a request feature 🆒
