### ISSUE TITLE
node-resolve: setting options.module is deprecated, please override options.mainFields instead

### ISSUE THREAD

**Issue by ri7nz** [ri7nz/Edotensei#17]
At this project have an issue about 
```
node-resolve: setting options.module is deprecated, please override options.mainFields instead
```
![image](https://user-images.githubusercontent.com/16365952/56432234-ccdca580-62f6-11e9-874e-563c3e06da3f.png)

when star building packages. 

Needed Help to resolve this is an issue. 👍 

Thanks

**Comment by 108kb** [comment]
It seems the "warning" occurs from `microbundle` package instead from this codebase.

![Screen Shot 2019-04-20 at 00 00 45](https://user-images.githubusercontent.com/6561394/56434599-70ca4f00-62ff-11e9-9731-2915ff38a365.png)

When I change the code from `node_modules/microbundle/dist/microbundle.js`, the warning was gone:

```diff
...
      })), nodeResolve({
+      mainFields: ['jsnext:main']
-      module: true,
-      jsnext: true,
-      browser: options.target !== 'node'
      }), commonjs({
...
```

Test is still passed

![Screen Shot 2019-04-20 at 00 07 35](https://user-images.githubusercontent.com/6561394/56434807-6bb9cf80-6300-11e9-812e-bc93375b4eb9.png)

**Comment by ri7nz** [comment]
@108kb  thank you so much, related on here https://github.com/developit/microbundle/pull/377/files

**Comment by 108kb** [comment]
Does bump the version of `microbundle` the problem still occurs?

**Comment by ri7nz** [comment]
@108kb  at this is PRs https://github.com/ri7nz/Edotensei/pull/19 has the latest version of `microbundle`
